---
- hosts: webservers
  become: true
  become_method: sudo

  vars:
    nginx_user: "root"
    nginx_sites:
      forest-community-blog:
        template: forest-community-blog.conf.j2

  roles:
    - "geerlingguy.java"
    - "ANXS.postgresql"
    - "jdauphant.nginx"

  tasks:
    - name: Create server dir
      file:
        path: "/root/forest_community_blog/server"
        state: directory

    - name: Create client dir
      file:
        path: "/root/forest_community_blog/client"
        state: directory

    - name: Create systemd config for forest-community-blog service
      template:
        src: "templates/forest-community-blog.service.j2"
        dest: "/etc/systemd/system/forest-community-blog.service"

    - name: Create environment file for forest-community-blog
      template:
        src: "templates/forest-community-blog.env.j2"
        dest: "/etc/profile.d/forest-community-blog"

    - name: Create database for forest community blog
      postgresql_db:
        name: forest_community_blog

    - name: Create root role for database
      postgresql_user:
        db: forest_community_blog
        name: root

    
