---
- hosts: webservers
  become: true
  become_method: sudo
  tasks:
    - name: Upload server jar
      copy:
        src: ../../target/server-standalone.jar
        dest: /var/www/forest-community-blog/server/app.jar
        
    - name: Upload client static
      unarchive:
        src: ../../target/client.tar.gz
        dest: /var/www/forest-community-blog/client
        directory_mode: yes
        mode: u+rwx

    - name: Migrate the database
      shell: java -cp app.jar clojure.main -m forest-community-blog.db migrate
      args:
        chdir: /var/www/forest-community-blog/server

    - name: Restart server service
      service:
        name: forest-community-blog
        state: restarted

